source: ./src
destination: ./site
name: Seichy's Missing Bit
description: 'A blog on programing, dreams, pandas and sweet food.'
url: http://martianwabbit.com
paginate: 4
markdown: redcarpet
sass:
    style: :compressed

host: 0.0.0.0
port: 4000
gems:
  - jekyll-redirect-from
  - jekyll-paginate
