source: ./src
destination: ./site
name: Seichy's Missing Bit
description: 'A blog on programing, dreams, pandas and sweet food.'
url: http://martianwabbit.com
paginate: 6

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
    style: :compressed

host: 0.0.0.0
port: 4000
gems:
  - jekyll-redirect-from
  - jekyll-paginate
