# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: jekyll/jekyll:3.4

steps:
- script: jekyll build
  displayName: 'Building Site'

- script: rsync -a /srv/jekyll/site seich@martianwabbit.com:/home/seich/webapps/martianwabbitsite
  displayName: 'Syncing Site to Server'
