# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: echo 'JEKYLLGRAM_KEY=$JEKYLLGRAM_KEY' > .env
- script: docker-compose run site jekyll build
  displayName: Building Site

- script: rsync -a ./site seich@martianwabbit.com:/home/seich/webapps/martianwabbitsite
  displayName: 'Syncing Site to Server'
