trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: echo "JEKYLLGRAM_KEY=$JEKYLLGRAM_KEY" > .env
  displayName: Creating .env file

- script: cat .env
  
- script: docker-compose run site jekyll build
  displayName: Building Site

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Martian Wabbit'
    sourceFolder: './site'
    contents: '**'
    targetFolder: '/home/seich/webapps/martianwabbitsite'