version: '3'

services:
  site:
    command: jekyll serve --force_polling --incremental
    image: jekyll/jekyll:3.4
    volumes:
      - .:/srv/jekyll
      - ./bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000