version: '3'

services:
  site:
    env_file: .env
    command: jekyll serve --force_polling --drafts
    image: jekyll/jekyll@sha256:d1bf33637d476e3cb2d5858038673cc93bc961e9390d31171d9febde5c5d24fd
    volumes:
      - .:/srv/jekyll
      - ./bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
