name: Deploy Website

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Creating .env file
      run: echo "JEKYLLGRAM_KEY=${{ secrets.JEKYLLGRAM_KEY }}" > .env
    - name: Adding Private Key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - uses: actions/cache@v1
      with:
        path: ./bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Building Site
      run: |
        mkdir -p ./src/.jekyll-cache/Jekyll
        docker-compose run site jekyll build --trace
    - name: Deploying site...
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=accept-new" -azP ./site/ ${{ secrets.REMOTE_USER }}:/home/seich/webapps/martianwabbitsite
      
