name: Deploy Website

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Creating .env file
      run: echo "${{ secrets.JEKYLLGRAM_KEY }}" > .env
    - name: Adding Private Key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Building Site
      run: docker-compose run site jekyll build
    - name: Deploying site...
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=accept-new" -azP ./site/ ${{ secrets.REMOTE_USER }}:/home/seich/webapps/martianwabbitsite
      
