name: Deploy Website

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Creating .env file
      run: echo "JEKYLLGRAM_KEY=${{ secrets.JEKYLLGRAM_KEY }}" > .env

    - name: Adding Private Key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - uses: actions/cache@v1.1.2
      with:
        path: ./bundle
        key: gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Building Site
      run: |
        mkdir ./site 
        mkdir -p ./src/.jekyll-cache/Jekyll/Cache/Jekyll--Cache
        docker-compose run site jekyll build --trace

    - name: Deploying site...
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=accept-new" -azP ./site/ ${{ secrets.REMOTE_USER }}:/home/seich/webapps/martianwabbitsite
      
