name: Deploy Website

on: 
  push:
    branches: 
      - disabled

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Creating .env file
      run: |
        echo "FLICKR_KEY=${{secrets.FLICKR_KEY}}" > .env
        echo "FLICKR_USER=${{secrets.FLICKR_USER}}" >> .env

    - name: Adding Private Key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - uses: actions/cache@v1.1.2
      with:
        path: ./bundle
        key: gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Building Site
      run: |
        mkdir ./site 
        mkdir -p ./src/.jekyll-cache
        chmod -R 0777 ./
        docker-compose run site jekyll build --trace
        

    - name: Deploying site...
      run: |
        rsync -e "ssh -o StrictHostKeyChecking=accept-new" -azP ./site/ ${{ secrets.REMOTE_USER }}:/home/seich/webapps/martianwabbitsite
      
