name: Deploy Website

on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Creating .env file
      run: |
        echo "FLICKR_KEY=${{ secrets.FLICKR_KEY }}" > .env
        echo "FLICKR_USER=${{ secrets.FLICKR_USER }}" >> .env

    - name: Setup known_hosts
      run: echo "${{ secrets.HOST_FINGERPRINT }}" > known_hosts

    - name: Adding Private Key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - uses: actions/cache@v1.1.2
      with:
        path: ./bundle
        key: gems-${{ hashFiles('**/Gemfile.lock') }}

    - name: Building Site
      run: |
        mkdir ./site 
        mkdir -p ./src/.jekyll-cache
        chmod -R 0777 ./
        docker-compose run site jekyll build --trace
        touch ./site/.static
        

    - name: Deploying site...
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: ${{ secrets.REMOTE_HOST }}
        BRANCH: master
        FOLDER: site
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        KNOWN_HOSTS_FILE: known_hosts
